"""Regenerates js/data.js from the SQL output files in data/ (sql_current_project_Q1.csv ... Q23.csv).
Run from anywhere:  python3 tools/build_data.py
Numbers are copied from the CSVs unchanged; nothing is typed in by hand."""
import csv, json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TITLES = {1:'Overall visitor funnel counts',2:'Funnel conversion rates',3:'Funnel drop-off',4:'Sequential View → Cart → Purchase',
 5:'Cart users without recorded purchase',6:'Purchases without preceding recorded cart',7:'Average events per visitor',
 8:'One-event vs multiple-event visitors',9:'Most active visitors',10:'Daily activity',11:'Daily event types',
 12:'Daily visitor-to-purchase conversion',13:'Category activity',14:'Category observed conversion',
 15:'Categories with many views and few purchases',16:'Availability activity',17:'Availability vs observed conversion',
 18:'Products with most views',19:'Products with strongest observed view-to-purchase conversion',
 20:'Products with many views and no recorded purchase',21:'Products with strong cart activity but relatively lower cart-to-purchase conversion',
 22:'Category enrichment completeness',23:'Availability enrichment completeness'}
TEXT = {'itemid','visitorid','categoryid','event_date','availability_status','visitor_type','category_status'}
def conv(k, v):
    if k in TEXT: return v
    try: return int(v)
    except ValueError: return float(v)
q = {}
for i in range(1, 24):
    with open(os.path.join(ROOT, 'data', f'sql_current_project_Q{i}.csv'), newline='', encoding='utf-8') as f:
        q[f'Q{i}'] = [{k: conv(k, v) for k, v in row.items()} for row in csv.DictReader(f)]
meta = {'title': 'E-Commerce Conversion Analytics',
        'description': 'SQL-driven analysis of browsing, cart and purchase activity: funnel, visitor behaviour, categories, products, availability and data quality. This is an observational analysis, not a causal study.',
        'businessQuestion': 'How effectively does the e-commerce platform turn customer browsing activity into purchases, and what factors are associated with conversion?',
        'source': 'E-Commerce Conversion Analytics \u00b7 SQL-driven observational analysis. Source: SQL outputs Q1 to Q23; every figure is traceable to the query tag on its card.'}
# Project figures validated earlier, not part of Q1-Q23; shown on the data-quality page with that label.
validated = {'uniqueItems': 235061, 'uniqueTransactionIds': 17672}
lines = ['/* GENERATED by tools/build_data.py from data/*.csv. Do not edit by hand. */', 'window.DASH = {']
lines.append(' meta: ' + json.dumps(meta, ensure_ascii=False) + ',')
lines.append(' validated: ' + json.dumps(validated) + ',')
lines.append(' queries: ' + json.dumps({f'Q{k}': v for k, v in TITLES.items()}, ensure_ascii=False) + ',')
lines.append(' q: {')
lines += ['  ' + json.dumps(k) + ': ' + json.dumps(v, ensure_ascii=False) + (',' if k != 'Q23' else '') for k, v in q.items()]
lines += [' }', '};']
open(os.path.join(ROOT, 'js', 'data.js'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('data.js written:', sum(len(v) for v in q.values()), 'rows from', len(q), 'queries')
